language: cpp
compiler: gcc

before_install:
  # C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  # C++17
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  # proselint
  - sudo pip install proselint

script: 
  - for filename in `ls *.md`; do proselint $filename; done
  - proselint Faq.md
  - cd hello
  - ./test_tests
  - cd ..
  - cd hello_world
  - ./test_tests
  - cd ..
  - cd hello_cli
  - ./test_tests
  - cd ..
  - cd is_odd
  - cp accept_0.cpp main.cpp; ./build; ./test
  - ./test_tests
  - cd ..

