language: cpp
compiler: gcc

before_install:
  # C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  # C++17
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  # proselint
  - sudo pip install proselint pdflatex
  # Creating a booklet
  - sudo apt-get install pandoc bookletimposer poppler-utils

script: 
  # proselint
  - for filename in `ls *.md`; do proselint $filename; done
  - cd doc
  - for filename in `ls *.md`; do proselint $filename; done
  - cd ..
  # test if all chapters' tests reject and accept answers correctly
  - ./test_tests
  # See if the book can be created
  - cd scripts
  - ./create_title_page
  - ./create_book
